var count = 1;
$('#1').show();
$("#2").hide();
$("#3").hide();
$("#4").hide();
$("#5").hide();
$("#6").hide();
$("#7").hide();
$("#8").hide();
$("#9").hide();
$("#10").hide();
var n1 = document.getElementById("number1");
var n2 = document.getElementById("number2");
var n3 = document.getElementById("number3");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
ctx1.fillText("2",10,50);
ctx2.fillText("1",30,50);
ctx3.fillText("3",50,50);

$('#submit').on('click', () => {
    count = count+1;
    console.log("...",count);
    if(count==1) {
        $('#1').show();
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number1");
        var n2 = document.getElementById("number2");
        var n3 = document.getElementById("number3");
        var ctx1 = n1.getContext("2d");
        var ctx2 = n2.getContext("2d");
        var ctx3 = n3.getContext("2d");
        ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("2",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } else if(count == 2) {
        $("#1").hide();
        $('#2').show();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number4");
var n2 = document.getElementById("number5");
var n3 = document.getElementById("number6");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("1",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } else if (count == 3) {
        $("#1").hide();
        $("#2").hide();
        $("#3").show();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number7");
var n2 = document.getElementById("number8");
var n3 = document.getElementById("number9");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("2",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } else if(count==4) {
        $("#2").hide();
        $("#3").hide();
        $("#1").hide();
        $("#4").show();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number10");
var n2 = document.getElementById("number11");
var n3 = document.getElementById("number12");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("3",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } else if(count == 5) {
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#1").hide();
        $('#5').show();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number13");
var n2 = document.getElementById("number14");
var n3 = document.getElementById("number15");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("3",10,50);
        ctx2.fillText("3",30,50);
        ctx3.fillText("3",50,50);
    } else if(count == 6) {
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#1").hide();
        $("#6").show();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number16");
var n2 = document.getElementById("number17");
var n3 = document.getElementById("number18");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("1",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } else if (count == 7) {
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#1").hide();
        $("#7").show();
        $("#8").hide();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number19");
var n2 = document.getElementById("number20");
var n3 = document.getElementById("number21");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("1",10,50);
        ctx2.fillText("2",30,50);
        ctx3.fillText("3",50,50);
    } else if (count == 8) {
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#1").hide();
        $("#8").show();
        $("#9").hide();
        $("#10").hide();
        var n1 = document.getElementById("number22");
var n2 = document.getElementById("number23");
var n3 = document.getElementById("number24");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("3",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } else if (count == 9) {
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#1").hide();
        $("#9").show();
        $("#10").hide();
        var n1 = document.getElementById("number25");
var n2 = document.getElementById("number26");
var n3 = document.getElementById("number27");

var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("2",10,50);
        ctx2.fillText("2",30,50);
        ctx3.fillText("3",50,50);
    } else {
        $("#2").hide();
        $("#3").hide();
        $("#4").hide();
        $("#5").hide();
        $("#6").hide();
        $("#7").hide();
        $("#8").hide();
        $("#9").hide();
        $("#1").hide();
        $("#10").show();
        var n1 = document.getElementById("number28");
var n2 = document.getElementById("number29");
var n3 = document.getElementById("number30");
var ctx1 = n1.getContext("2d");
var ctx2 = n2.getContext("2d");
var ctx3 = n3.getContext("2d");
ctx1.font = ctx2.font = ctx3.font = "30px Arial";
        ctx1.fillText("1",10,50);
        ctx2.fillText("1",30,50);
        ctx3.fillText("3",50,50);
    } 
});